STEP 1.1 — IMPORT LIBRARY

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

STEP 1.2 — LOAD DATASET

In [2]:
DATA_PATH = "../data/raw/government_public_sentiment_dataset.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,comment_id,platform,program_name,comment_text,sentiment,likes,replies,engagement_score,hashtags,topic_category,city_region,created_at,user_type,urgency_level
0,CMT-100001,TikTok,WiFi Publik Kota Batu,Semoga layanan terus ditingkatkan.,Neutral,2258,125,2508,#DiskominfoBatu,Pendidikan,Pasuruan,2025-08-19 16:38:09,Tourist,Medium
1,CMT-100002,Twitter/X,Smart City Batu,Program ini sangat membantu masyarakat.,Positive,1796,119,2034,#PelayananPublik,Teknologi,Malang,2025-08-21 18:11:47,Tourist,Low
2,CMT-100003,Instagram,E-Government Service,Semoga layanan terus ditingkatkan.,Neutral,1312,357,2026,#UMKMBatu,UMKM,Malang,2025-05-26 21:25:17,UMKM Owner,Medium
3,CMT-100004,Instagram,Batu Tourism App,Salut untuk inovasi digital Kota Batu.,Positive,797,183,1163,#SmartCityBatu,Ekonomi Digital,Pasuruan,2025-06-17 18:10:55,Citizen,Low
4,CMT-100005,Twitter/X,E-Government Service,Informasi di aplikasi kurang update.,Negative,4527,150,4827,#PelayananPublik,Pendidikan,Batu,2025-09-17 14:28:25,Student,Medium

STEP 1.3 — DATA OVERVIEW

In [3]:
print("Dataset Shape:", df.shape)
df.info()
df.describe(include='all')

Dataset Shape: (5000, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   comment_id        5000 non-null   object
 1   platform          5000 non-null   object
 2   program_name      5000 non-null   object
 3   comment_text      5000 non-null   object
 4   sentiment         5000 non-null   object
 5   likes             5000 non-null   int64
 6   replies           5000 non-null   int64
 7   engagement_score  5000 non-null   int64
 8   hashtags          5000 non-null   object
 9   topic_category    5000 non-null   object
 10  city_region       5000 non-null   object
 11  created_at        5000 non-null   object
 12  user_type         5000 non-null   object
 13  urgency_level     5000 non-null   object
dtypes: int64(3), object(11)
memory usage: 547.0+ KB

,comment_id,platform,program_name,comment_text,sentiment,likes,replies,engagement_score,hashtags,topic_category,city_region,created_at,user_type,urgency_level
count,5000,5000,5000,5000,5000,5000.000000,5000.000000,5000.000000,5000,5000,5000,5000,5000,5000
unique,5000,3,8,24,3,NaN,NaN,NaN,8,8,6,4999,5,3
top,CMT-100001,Twitter/X,Digital Learning Batu,Informasi publik jadi lebih transparan.,Positive,NaN,NaN,NaN,#KotaBatu,Ekonomi Digital,Blitar,2025-09-19 19:51:58,Public Employee,Low
freq,1,1686,652,382,2768,NaN,NaN,NaN,661,674,870,2,1020,2768
mean,NaN,NaN,NaN,NaN,NaN,2488.155000,251.720400,2991.595800,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,1446.805992,144.376373,1476.923846,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,5.000000,0.000000,27.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,1225.000000,128.000000,1718.750000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,2498.000000,254.000000,3012.500000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,3729.000000,379.000000,4235.250000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,5000.000000,500.000000,5996.000000,NaN,NaN,NaN,NaN,NaN,NaN

STEP 1.4 — CHECK MISSING VALUES

In [4]:
missing_values = df.isnull().sum()

missing_values

comment_id          0
platform            0
program_name        0
comment_text        0
sentiment           0
likes               0
replies             0
engagement_score    0
hashtags            0
topic_category      0
city_region         0
created_at          0
user_type           0
urgency_level       0
dtype: int64

VISUAL MISSING VALUE

In [5]:
missing_df = pd.DataFrame({
    'column': missing_values.index,
    'missing_count': missing_values.values
})

fig = px.bar(
    missing_df,
    x='column',
    y='missing_count',
    title='Missing Value Analysis',
    template='plotly_dark',
    color='missing_count'
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

STEP 1.5 — CHECK DUPLICATE

In [6]:
duplicate_count = df.duplicated().sum()

print(f"Duplicate Rows: {duplicate_count}")

Duplicate Rows: 0

REMOVE DUPLICATE

In [7]:
df = df.drop_duplicates()

STEP 1.6 — TEXT CLEANING

CLEAN TEXT FUNCTION

In [8]:
import re

In [9]:
def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\\S+", "", text)

    text = re.sub(r"@\\w+", "", text)

    text = re.sub(r"#", "", text)

    text = re.sub(r"[^a-zA-Z\\s]", "", text)

    text = re.sub(r"\\s+", " ", text)

    return text.strip()

APPLY CLEANING

In [10]:
df['clean_comment'] = df['comment_text'].apply(clean_text)

BEFORE VS AFTER

In [11]:
comparison_df = df[[
    'comment_text',
    'clean_comment'
]]

comparison_df.head()

                              comment_text                       clean_comment
0       Semoga layanan terus ditingkatkan.      semogalayananterusditingkatkan
1  Program ini sangat membantu masyarakat.  programinisangatmembantumasyarakat
2       Semoga layanan terus ditingkatkan.      semogalayananterusditingkatkan
3   Salut untuk inovasi digital Kota Batu.    salutuntukinovasidigitalkotabatu
4     Informasi di aplikasi kurang update.     informasidiaplikasikurangupdate

STEP 1.7 — SENTIMENT DISTRIBUTION

In [12]:
sentiment_count = df['sentiment'].value_counts()

sentiment_count

sentiment
Positive    2768
Neutral     1484
Negative     748
Name: count, dtype: int64

VISUAL

In [13]:
fig = px.pie(
    values=sentiment_count.values,
    names=sentiment_count.index,
    hole=0.6,
    title='Public Sentiment Distribution',
    template='plotly_dark',
    color_discrete_map={
        'Positive': '#22C55E',
        'Neutral': '#3B82F6',
        'Negative': '#EF4444'
    }
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white',
    title_font_size=24
)

fig.show()

STEP 1.8 — CONVERT DATETIME

In [14]:
df['created_at'] = pd.to_datetime(
    df['created_at']
)

EXTRACT DATE FEATURE

In [15]:
df['year'] = df['created_at'].dt.year

df['month'] = df['created_at'].dt.month

df['day'] = df['created_at'].dt.day

STEP 1.9 — ENGAGEMENT CATEGORY

In [16]:
df['engagement_category'] = pd.cut(
    df['engagement_score'],
    bins=[0, 1000, 3000, 10000],
    labels=[
        'Low',
        'Medium',
        'High'
    ]
)

CEK HASIL

In [17]:
df[['engagement_score',
    'engagement_category']].head()

   engagement_score engagement_category
0              2508              Medium
1              2034              Medium
2              2026              Medium
3              1163              Medium
4              4827                High

STEP 1.10 — SAVE CLEAN DATASET

In [19]:
SAVE_PATH = "../data/processed/clean_public_sentiment.csv"

df.to_csv(
    SAVE_PATH,
    index=False
)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.